def SetUseSoundFileName():
	pass

def SetDropSoundFileName():
	pass

def SelectItem():
	pass

def GetItemName():
	pass

def GetItemDescription():
	pass

def GetItemSummary():
	pass

def GetIconImage():
	pass

def GetIconImageFileName():
	pass

def GetItemSize():
	pass

def GetItemType():
	pass

def GetItemSubType():
	pass

def GetIBuyItemPrice():
	pass

def GetISellItemPrice():
	pass

def IsAntiFlag():
	pass

def IsFlag():
	pass

def IsWearableFlag():
	pass

def Is1GoldItem():
	pass

def GetLimit():
	pass

def GetAffect():
	pass

def GetValue():
	pass

def GetSocket():
	pass

def GetIconInstance():
	pass

def GetUseType():
	pass

def DeleteIconInstance():
	pass

def IsEquipmentVID():
	pass

def IsRefineScroll():
	pass

def IsDetachScroll():
	pass

def IsKey():
	pass

def IsMetin():
	pass

def CanAddToQuickSlotItem():
	pass

def Update():
	pass

def Render():
	pass

def CreateItem():
	pass

def DeleteItem():
	pass

def Pick():
	pass

def LoadItemTable():
	pass

USESOUND_ACCESSORY = None
USESOUND_ARMOR = None
USESOUND_BOW = None
USESOUND_DEFAULT = None
USESOUND_WEAPON = None
USESOUND_POTION = None
USESOUND_PORTAL = None
DROPSOUND_ACCESSORY = None
DROPSOUND_ARMOR = None
DROPSOUND_BOW = None
DROPSOUND_DEFAULT = None
DROPSOUND_WEAPON = None
EQUIPMENT_COUNT = None
EQUIPMENT_HEAD = None
EQUIPMENT_BODY = None
EQUIPMENT_WEAPON = None
EQUIPMENT_WRIST = None
EQUIPMENT_SHOES = None
EQUIPMENT_NECK = None
EQUIPMENT_EAR = None
EQUIPMENT_UNIQUE1 = None
EQUIPMENT_UNIQUE2 = None
EQUIPMENT_ARROW = None
EQUIPMENT_RING1 = None
EQUIPMENT_RING2 = None
EQUIPMENT_BELT = None
ITEM_TYPE_NONE = None
ITEM_TYPE_WEAPON = None
ITEM_TYPE_ARMOR = None
ITEM_TYPE_USE = None
ITEM_TYPE_AUTOUSE = None
ITEM_TYPE_MATERIAL = None
ITEM_TYPE_SPECIAL = None
ITEM_TYPE_TOOL = None
ITEM_TYPE_LOTTERY = None
ITEM_TYPE_ELK = None
ITEM_TYPE_METIN = None
ITEM_TYPE_CONTAINER = None
ITEM_TYPE_FISH = None
ITEM_TYPE_ROD = None
ITEM_TYPE_RESOURCE = None
ITEM_TYPE_CAMPFIRE = None
ITEM_TYPE_UNIQUE = None
ITEM_TYPE_SKILLBOOK = None
ITEM_TYPE_QUEST = None
ITEM_TYPE_POLYMORPH = None
ITEM_TYPE_TREASURE_BOX = None
ITEM_TYPE_TREASURE_KEY = None
ITEM_TYPE_PICK = None
ITEM_TYPE_BLEND = None
ITEM_TYPE_DS = None
ITEM_TYPE_SPECIAL_DS = None
ITEM_TYPE_RING = None
ITEM_TYPE_BELT = None
ITEM_TYPE_COSTUME = None
COSTUME_TYPE_BODY = None
COSTUME_TYPE_HAIR = None
COSTUME_SLOT_START = None
COSTUME_SLOT_COUNT = None
COSTUME_SLOT_BODY = None
COSTUME_SLOT_HAIR = None
COSTUME_SLOT_END = None
BELT_INVENTORY_SLOT_START = None
BELT_INVENTORY_SLOT_COUNT = None
BELT_INVENTORY_SLOT_END = None
WEAPON_SWORD = None
WEAPON_DAGGER = None
WEAPON_BOW = None
WEAPON_TWO_HANDED = None
WEAPON_BELL = None
WEAPON_FAN = None
WEAPON_ARROW = None
WEAPON_NUM_TYPES = None
USE_POTION = None
USE_TALISMAN = None
USE_TUNING = None
USE_MOVE = None
USE_TREASURE_BOX = None
USE_MONEYBAG = None
USE_BAIT = None
USE_ABILITY_UP = None
USE_AFFECT = None
USE_CREATE_STONE = None
USE_SPECIAL = None
USE_POTION_NODELAY = None
USE_CLEAR = None
USE_INVISIBILITY = None
USE_DETACHMENT = None
USE_TIME_CHARGE_PER = None
USE_TIME_CHARGE_FIX = None
MATERIAL_DS_REFINE_NORMAL = None
MATERIAL_DS_REFINE_BLESSED = None
MATERIAL_DS_REFINE_HOLLY = None
METIN_NORMAL = None
METIN_GOLD = None
LIMIT_NONE = None
LIMIT_LEVEL = None
LIMIT_STR = None
LIMIT_DEX = None
LIMIT_INT = None
LIMIT_CON = None
LIMIT_PCBANG = None
LIMIT_REAL_TIME = None
LIMIT_REAL_TIME_START_FIRST_USE = None
LIMIT_TIMER_BASED_ON_WEAR = None
LIMIT_TYPE_MAX_NUM = None
LIMIT_MAX_NUM = None
ITEM_ANTIFLAG_FEMALE = None
ITEM_ANTIFLAG_MALE = None
ITEM_ANTIFLAG_WARRIOR = None
ITEM_ANTIFLAG_ASSASSIN = None
ITEM_ANTIFLAG_SURA = None
ITEM_ANTIFLAG_SHAMAN = None
ITEM_ANTIFLAG_GET = None
ITEM_ANTIFLAG_DROP = None
ITEM_ANTIFLAG_SELL = None
ITEM_ANTIFLAG_EMPIRE_A = None
ITEM_ANTIFLAG_EMPIRE_B = None
ITEM_ANTIFLAG_EMPIRE_R = None
ITEM_ANTIFLAG_SAVE = None
ITEM_ANTIFLAG_GIVE = None
ITEM_ANTIFLAG_PKDROP = None
ITEM_ANTIFLAG_STACK = None
ITEM_ANTIFLAG_MYSHOP = None
ITEM_FLAG_RARE = None
ITEM_FLAG_UNIQUE = None
ITEM_FLAG_CONFIRM_WHEN_USE = None
ANTIFLAG_FEMALE = None
ANTIFLAG_MALE = None
ANTIFLAG_WARRIOR = None
ANTIFLAG_ASSASSIN = None
ANTIFLAG_SURA = None
ANTIFLAG_SHAMAN = None
ANTIFLAG_GET = None
ANTIFLAG_DROP = None
ANTIFLAG_SELL = None
ANTIFLAG_EMPIRE_A = None
ANTIFLAG_EMPIRE_B = None
ANTIFLAG_EMPIRE_R = None
ANTIFLAG_SAVE = None
ANTIFLAG_GIVE = None
ANTIFLAG_PKDROP = None
ANTIFLAG_STACK = None
ANTIFLAG_MYSHOP = None
WEARABLE_BODY = None
WEARABLE_HEAD = None
WEARABLE_FOOTS = None
WEARABLE_WRIST = None
WEARABLE_WEAPON = None
WEARABLE_NECK = None
WEARABLE_EAR = None
WEARABLE_UNIQUE = None
WEARABLE_SHIELD = None
WEARABLE_ARROW = None
ARMOR_BODY = None
ARMOR_HEAD = None
ARMOR_SHIELD = None
ARMOR_WRIST = None
ARMOR_FOOTS = None
ARMOR_NECK = None
ARMOR_EAR = None
ITEM_APPLY_MAX_NUM = None
ITEM_SOCKET_MAX_NUM = None
APPLY_NONE = None
APPLY_STR = None
APPLY_DEX = None
APPLY_CON = None
APPLY_INT = None
APPLY_MAX_HP = None
APPLY_MAX_SP = None
APPLY_HP_REGEN = None
APPLY_SP_REGEN = None
APPLY_DEF_GRADE_BONUS = None
APPLY_ATT_GRADE_BONUS = None
APPLY_ATT_SPEED = None
APPLY_MOV_SPEED = None
APPLY_CAST_SPEED = None
APPLY_MAGIC_ATT_GRADE = None
APPLY_MAGIC_DEF_GRADE = None
APPLY_SKILL = None
APPLY_ATTBONUS_ANIMAL = None
APPLY_ATTBONUS_UNDEAD = None
APPLY_ATTBONUS_DEVIL = None
APPLY_ATTBONUS_HUMAN = None
APPLY_BOW_DISTANCE = None
APPLY_RESIST_BOW = None
APPLY_RESIST_FIRE = None
APPLY_RESIST_ELEC = None
APPLY_RESIST_MAGIC = None
APPLY_POISON_PCT = None
APPLY_SLOW_PCT = None
APPLY_STUN_PCT = None
APPLY_CRITICAL_PCT = None
APPLY_PENETRATE_PCT = None
APPLY_ATTBONUS_ORC = None
APPLY_ATTBONUS_MILGYO = None
APPLY_ATTBONUS_UNDEAD = None
APPLY_ATTBONUS_DEVIL = None
APPLY_STEAL_HP = None
APPLY_STEAL_SP = None
APPLY_MANA_BURN_PCT = None
APPLY_DAMAGE_SP_RECOVER = None
APPLY_BLOCK = None
APPLY_DODGE = None
APPLY_RESIST_SWORD = None
APPLY_RESIST_TWOHAND = None
APPLY_RESIST_DAGGER = None
APPLY_RESIST_BELL = None
APPLY_RESIST_FAN = None
APPLY_RESIST_WIND = None
APPLY_REFLECT_MELEE = None
APPLY_REFLECT_CURSE = None
APPLY_POISON_REDUCE = None
APPLY_KILL_SP_RECOVER = None
APPLY_EXP_DOUBLE_BONUS = None
APPLY_GOLD_DOUBLE_BONUS = None
APPLY_ITEM_DROP_BONUS = None
APPLY_POTION_BONUS = None
APPLY_KILL_HP_RECOVER = None
APPLY_IMMUNE_STUN = None
APPLY_IMMUNE_SLOW = None
APPLY_IMMUNE_FALL = None
APPLY_MAX_STAMINA = None
APPLY_ATTBONUS_WARRIOR = None
APPLY_ATTBONUS_ASSASSIN = None
APPLY_ATTBONUS_SURA = None
APPLY_ATTBONUS_SHAMAN = None
APPLY_ATTBONUS_MONSTER = None
APPLY_MALL_ATTBONUS = None
APPLY_MALL_DEFBONUS = None
APPLY_MALL_EXPBONUS = None
APPLY_MALL_ITEMBONUS = None
APPLY_MALL_GOLDBONUS = None
APPLY_MAX_HP_PCT = None
APPLY_MAX_SP_PCT = None
APPLY_SKILL_DAMAGE_BONUS = None
APPLY_NORMAL_HIT_DAMAGE_BONUS = None
APPLY_SKILL_DEFEND_BONUS = None
APPLY_NORMAL_HIT_DEFEND_BONUS = None
APPLY_PC_BANG_EXP_BONUS = None
APPLY_PC_BANG_DROP_BONUS = None
APPLY_RESIST_WARRIOR = None
APPLY_RESIST_ASSASSIN = None
APPLY_RESIST_SURA = None
APPLY_RESIST_SHAMAN = None
APPLY_ENERGY = None
APPLY_COSTUME_ATTR_BONUS = None
APPLY_MAGIC_ATTBONUS_PER = None
APPLY_MELEE_MAGIC_ATTBONUS_PER = None
APPLY_RESIST_ICE = None
APPLY_RESIST_EARTH = None
APPLY_RESIST_DARK = None
APPLY_ANTI_CRITICAL_PCT = None
APPLY_ANTI_PENETRATE_PCT = None
